### ISSUE TITLE
confused about configuration

### ISSUE THREAD

**Issue by redlandmover** [kylerw/MiscScripts#1]
hey. i really would like to use your script, but im a bit confused about how to go about hooking this script into the linuxserver's base docker image. 

is there a specific place i drop this script in the unraid ui? or do i go into the docker image and add the script? or ____?

sorry if this isn't the place for this sort of discussion. thanks for posting this!

**Comment by kylerw** [comment]
@redlandmover hey, LS recently changed their base images to Alpine Linux so it no longer is automated, unfortunately. Process for now is to manually run the Alpine version from within the container. Make sure you add a mapping to /mp4automator which is where it will install.


I can give a more detailed guide tomorrow if you'd like.

**Comment by redlandmover** [comment]
@kylerw that would be very much appreciated. im going to try to take a stab at it tonight, now that im armed with your comment, but any help would be very appreciated.

**Comment by kylerw** [comment]
Ok, here is some more detail:

Make sure your container has a mapping for:
/scripts (/mnt/cache/Apps/scripts)
/mp4automator (/mnt/cache/Apps/mp4automator)

Place the Alpine version of the script in your NZBGet config directory (mine is named userscript.sh)

then attach to a bash terminal inside the NZBGet container:
docker exec -it NZBGet bash

then run:
sh /config/userscript.sh

This will install dependencies, clone mp4automator, and place the script in the /script folder which will then need to be mapped into NZBGet. To do this:
Settings --> Paths --> ScriptDir should be /scripts 

Once NZBGet reloads you should have a new option in Settings at the bottom. Select NZBGETPOSTPROCESS.

Here:
MP4_FOLDER: /mp4automator
then setup the categories appropriately for your setup.

**Comment by kylerw** [comment]
You will also want to then follow the MP4automator setup to edit the autoProcess.ini accordingly. ffmpeg installs to: /usr/bin/ffmpeg and /usr/bin/ffprobe
